import React from "react";
import "../styles/formalities.css"

export const Formalities = () => {
    const formaliteList = ['Aceptación de árbitro', 
        'Adjudicación de sitio en loteo de población', 
        'Adjudicación en remate público', 
        'Administración de fundo', 
        'Administrador pro indiviso',
        'Alzamiento de Prenda',
        'Arrendamiento (de panadería)',
        'Arrendamiento de bien raíz urbano',
        'Arrendamiento de predios agrícolas',
        'Arrendamiento de un predio agrícola',
        'Arrendamiento Invalidación por consentimiento mutuo',
        'Arrendamiento Terminación',
        'Arrendamiento Terminación alzamiento y finiquito',
        'Asociación o cuentas en participación',
        'Asociación profesional',
        'Autorización de la mujer al marido para vender un bien raíz perteneciente a la sociedad conyugal',
        'Autorización de la mujer al marido para vender un inmueble',
        'Autorización del marido a la cónyuge para abrir cuenta corriente',
        'Autorización para abrir cuenta corriente',
        'Cancelación de mutuo hipotecario',
        'Cancelación de precio pagadero en cuotas',
        'Cancelación de saldo de precio',
        'Capitulaciones matrimoniales',
        'Cesión de Crédito',
        'Cesión de derechos hereditarios',
        'Cesión de derechos litigiosos',
        'Compraventa con pacto de retroventa',
        'Compraventa de departamento',
        'Compraventa de inmueble que adquieren marido y mujer (separados de bienes) como usufructuario y nuda propietaria respectivamente',
        'Compraventa de lotes de terreno',
        'Compraventa de negocio',
        'Compraventa de predio agrícola (afecto a posible expropiación y pago saldo reajustado al precio oficial del trigo)',
        'Compraventa de predio agrícola con parte del predio reajustado',
        'Compraventa de predio agrícola',
        'Compraventa de propiedad urbana',
        'Compraventa en remate judicial',
        'Comunidad de desagües',
        'Confección de obra material',
        'Convenio de honorarios',
        'Corretaje de venta de bien raíz por lotes',
        'Dación en pago',
        'Dación en pago condicional',
        'Delegación de mandato judicial',
        'Delegación de poder',
        'Derecho de habitación',
        'Derechos de uso y habitación',
        'Disolución de sociedad',
        'Disolución y liquidación de comunidad',
        'Donación',
        'Emancipación',
        'Entrega de legado',
        'Estatutos de Club Social',
        'Expropiación (ensanche de calle)',
        'Fianza (empleados)',
        'Fianza bancaria',
        'Fianza en garantía de servicios',
        'Fianza nominal',
        'Finiquito',
        'Garantía general (administración)',
        'Garantía general bancaria',
        'Iguala',
        'Legitimación',
        'Liberación de hipoteca',
        'Liberación de obligación',
        'Liberación de solidaridad',
        'Liquidación de comunidad (predio agrícola)',
        'Liquidación de sociedad conyugal',
        'Liquidación de sociedad conyugal (extranjeros)',
        'Liquidación de sociedad conyugal participación y adjudicaciones',
        'Mandatario común',
        'Mandato (para tramitación patente y otros ante la Dirección de Industria y Comercio)',
        'Mandato (trámites sucesorios y liquidación de bienes)',
        'Mandato especial (para actuar en España)',
        'Mandato especial (para contraer matrimonio)',
        'Mandato especial (para nulidad de matrimonio)',
        'Mandato especial (para obtener préstamo hipotecario en el Banco del Estado)',
        'Mandato especial de administración (camión)',
        'Mandato especial de administración de casas',
        'Mandato especial para administrar negocio',
        'Mandato especial para representar a una sociedad o establecimiento comercial',
        'Mandato especial para vender un inmueble',
        'Mandato especial y autorización marital para vender',
        'Mandato general',
        'Mandato general (otorgado en el extranjero para operaciones comerciales en Chile)',
        'Mandato general (para administración de comunidad)',
        'Mandato general (sucesión)',
        'Mandato judicial',
        'Mandato para administrar un bien raíz urbano',
        'Mandato para cobrar rentas de arrendamiento',
        'Mandato para comprar un terreno en comunidad',
        'Mandato para obtener y cobrar beneficios previsionales',
        'Mandato para operar en cuenta corriente bancaria',
        'Mandato para tramitar jubilación ante una Caja de Previsión',
        'Mandato para vender inmueble (adquirido en régimen de sociedad conyugal)',
        'Mandato y autorización (para vender los bienes propios de la cónyuge)',
        'Medianería',
        'Mutuo con garantía de hipoteca de usufructo',
        'Mutuo hipotecario',
        'Mutuo Prórroga',
        'Pacto de indivisión',
        'Pago con subrogación',
        'Participación',
        'Participación de utilidades',
        'Partidor (nombramiento)',
        'Pensión de alimentos',
        'Permiso de edificación',
        'Permuta de bien raíz y especie mueble',
        'Permuta de inmuebles',
        'Posposición de hipoteca',
        'Premanda para caucionar pago letra',
        'Prenda industrial',
        'Prenda para garantizar desempeño funciones director sociedad',
        'Promesa de compraventa (bien raíz)',
        'Promesa de compraventa (establecimiento de comercio)',
        'Promesa de compraventa de predio agrícola',
        'Promesa de compraventa de propiedad urbana',
        'Promesa de compraventa de un departamento en edificio en construcción',
        'Protesta',
        'Recibo',
        'Recibo cancelación y alzamiento',
        'Reconocimiento de deuda e hipoteca',
        'Reconocimiento de deuda y garantía prendaria',
        'Reconocimiento hijo natural',
        'Reglamento de Copropiedad de Edificio',
        'Renta vitalicia',
        'Renuncia de adopción',
        'Renuncia de gananciales',
        'Renuncia de mandato',
        'Renuncia de nacionalidad',
        'Renuncia de porción conyugal en virtud del derecho de opción legal',
        'Renuncia de usufructo',
        'Repudiación de herencia',
        'Resciliación',
        'Resciliación y finiquito',
        'Revocación de mandato especial',
        'Revocación de mandato general',
        'Revocación de testamento abierto',
        'Revocación de todo testamento',
        'Separación de bienes',
        'Separación de bienes y renuncia de gananciales',
        'Servidumbre',
        'Servidumbre de luz y vista',
        'Servidumbre de paso de línea de transmisión eléctrica',
        'Servidumbre de tránsito',
        'Servidumbre voluntaria de alcantarillado',
        'Sociedad (transformación de una sociedad de responsabilidad limitada en sociedad colectiva comercial)',
        'Sociedad anónima',
        'Sociedad colectiva civil',
        'Sociedad colectiva comercial',
        'Sociedad comercial de responsabilidad limitada',
        'Sociedad constructora de viviendas económicas (5% industria y comercio)',
        'Sociedad de hecho',
        'Sociedad de responsabilidad limitada',
        'Sociedad de responsabilidad limitada regida por un directorio',
        'Sociedad de responsabilidad limitada Modificación',
        'Sociedad en comandita simple',
        'Sociedad pesquera',
        'Término de fianza y solidaridad',
        'Testamento abierto',
        'Testamento abierto (terminación para el caso de que el testador o la testadora no sepa no pueda firmar)',
        'Testamento cerrado Carátula',
        'Testamento del ciego (cláusula final)',
        'Transacción'
    ]
    return (
        <>
            
            <div className="formalite-container">
                <p>----------Tramites Notariales---------</p>
                {formaliteList.map((tramite, index) => (
                    <div key={index} className="formalite-item">
                        {tramite}
                    </div>
                ))}
            </div>
        </>
    );
}